### ISSUE TITLE
Find Crosswalk of NCD to Encoded Archival Description (EAD) format

### ISSUE THREAD

**Issue by stanblum** [tdwg/ncd#11]
@connierinaldo mentioned that a crosswalk to EAD was done.  It would be good to post that crosswalk into this repository.  It would be good to for the TDWG community to embrace/follow/parallel? the EAD/Finding-Aid thinking of hierarchical collection descriptions.  

Also see these resources:
https://en.wikipedia.org/wiki/Encoded_Archival_Description
https://github.com/SAA-SDT/EAD3

**Comment by pmergen** [comment]
Brilliant ! That's the format used by Archive  Portal Europe and probably just what is needed for several of our projects.
Thanks
Pat

**Comment by connierinaldo** [comment]
I found the spreadsheet cross walk to Dublin Core but am still looking for the EAD one.  And keep in mind that these are 10 years old.  I will keep looking.

**Comment by connierinaldo** [comment]
I found the NCD/EAD comparison done by Barbara Mathe.  But the excel file type  is not supported (according to the error message) for dropping into this document.  So here is a crummy doc:
[NCD.docx](https://github.com/tdwg/ncd/files/1726168/NCD.docx)

**Comment by connierinaldo** [comment]
And here is the Dublin Core (more detailed).
[Natural Collection Descriptions Cross Walk to Dublin Core_ 11 May 2006.docx](https://github.com/tdwg/ncd/files/1726173/Natural.Collection.Descriptions.Cross.Walk.to.Dublin.Core_.11.May.2006.docx)

**Comment by pmergen** [comment]
Hi 
Check out them: https://www.archivesportaleurope.net/directory . Most  major archives, State, counties, institutions, many private archives association are connected in a standard way. They are a repository of archival unit. Old but also recent digital archives only are concerned. The natural history and bot garden of Belgium are in the process to be connected. Theb cans themselves are in europeana or other repositories or locally online if available. The interlinking of the archival unit and this digital object is not always trivial, but we are just busy setting up a project with them to be interconnect them, Europeana, gbif .... notably with the cetaf unic identifiers. If you would like to bring in this archival standard into crossmapping with NCD or Dublin Core their representatives might be interesting to contact. I pretty sure they cover dublin core, but not yet NCD. Let me know if you would find this interesting for tdwg ?

**Comment by stanblum** [comment]
Connie sent me the Excel spreadsheet.  I'll convert that to html or markdown and post to the repository.  Might start a wiki page for resources and their relevance to NCD.
