### ISSUE TITLE
please add use cases or link to them

### ISSUE THREAD

**Issue by debpaul** [tdwg/ncd#13]
@godfoder please upload Barb's NCD use cases to this folder:
https://github.com/tdwg/ncd/tree/master/crosswalks-related-docs

Then we can link her work here https://github.com/tdwg/ncd/wiki/Crosswalks-and-Use-Cases#use-cases-for-ncd

**Comment by stanblum** [comment]
- Index Herbariorum use-cases from Barbara Thiers uploaded as a markdown file; 
- renamed to use-cases.md;
- headings adjusted so that other use-cases can be added from other perspectives;
- may want to reformat / restructure these

**Comment by debpaul** [comment]
many thanks @stanblum
