### ISSUE TITLE
NCD Dublin Core

### ISSUE THREAD

**Issue by connierinaldo** [tdwg/ncd#18]
I don't remember if I added this in the right place but I did convert the Dublin Core/NCD crosswalk from word to a google spreadsheet, just in case it is relevant and I forgot, here is the link
https://docs.google.com/spreadsheets/d/1uUY1JlSV6QifdnZbkITrVJNf27bEZPJT_fSfYsAcvIY/edit?usp=sharing

**Comment by stanblum** [comment]
I'll add a link in the wiki to the NCD - Dublin Core crosswalk.

**Comment by stanblum** [comment]
I added a link to the Google sheet version of the NCD-DublinCore crosswalk, as well as an Excel file.

**Comment by connierinaldo** [comment]
Thanks.

Sent from my iPhone

On Mar 2, 2018, at 4:26 AM, Stan Blum <notifications@github.com<mailto:notifications@github.com>> wrote:


I added a link to the Google sheet version of the NCD-DublinCore crosswalk, as well as an Excel file.
